### ISSUE TITLE
.NET Standard version of the package 

### ISSUE THREAD

**Issue by kolappannathan** [saguiitay/serilog-sinks-azuredataexplorer#1]
Is it possible to release the Nuget package for .NET standard as well. Currently only .NET 6 is listed as supported.

Will be happy to work on it and submit a PR.

**Comment by tanmaya-panda1** [comment]
Currently only .NET 6 is supported and we have a PR(to be merged soon) to add durability support. We will be glad if you can contribute to support the standard versions.
