### ISSUE TITLE
Removed copyright notices

### ISSUE THREAD

**Issue by nblumhardt** [saguiitay/serilog-sinks-azuredataexplorer#16]
Hi! It's nice to see Serilog supported here.

This repository contains a number of files that appear to be derived from _Serilog.Sinks.Seq_, developed by myself and others through the Serilog project, in particular, most of the files in the `Serilog.Sinks.AzureDataExplorer.Durable` namespace.

These were provided under Apache 2.0, which requires:

>     (c) You must retain, in the Source form of any Derivative Works
>          that You distribute, all copyright, patent, trademark, and
>          attribution notices from the Source form of the Work,
>          excluding those notices that do not pertain to any part of
>          the Derivative Works; and

However, the copyright notices from the original source code appear to have been removed.

It would be appreciated if you could acknowledge the original authors by adding the notices back.

The source code suggests that the code was forked from _Serilog.Sinks.Seq_ 4.0.0, which you can now find a copy of at: https://github.com/datalust/serilog-sinks-seq/releases/tag/v4.0.0.

**Comment by kustonaut** [comment]
@nblumhardt Thank you for bringing this to our notice. Please accept our sincere apologies for the inadvertent omission. We have added back the notices as license headers in all the files through this PR: https://github.com/Azure/serilog-sinks-azuredataexplorer/pull/22 . We acknowledge and are grateful for your and all other community members' contribution to Serilog.

**Comment by nblumhardt** [comment]
Hi @kustonaut - thanks very much, that's greatly appreciated. Glad this code turned out to be useful here! 😎
