### ISSUE TITLE
Workload Identity support with appsettings.json

### ISSUE THREAD

**Issue by mitanshusharma** [saguiitay/serilog-sinks-azuredataexplorer#30]
Hello,

The appsetting.json support was added as part of the PR below: 
https://github.com/Azure/serilog-sinks-azuredataexplorer/pull/25/files#diff-aaa13739f85d462be9a7a3b3f057e19334b13b541d8f8b0e7a091c31370d1122 

Checking this PR , it seems that the only way to authenticate if we want to use appsettings.json configuration would be through Client Id and secret. 

Could it be possible to add the support for other authentication type (like workload Identity required in our case because of policies) using the appsettings.json .

Thanks for the help.

**Comment by ag-ramachandran** [comment]
This is now supported where workload identity flag can be set through config
